name: A
on:
  workflow_run:
    workflows: ['Test workflow with upload']
    types: [completed]

jobs:
  pr_comment:
    if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    
    steps:
      # - uses: 8BitJonny/gh-get-current-pr@2.1.3
      #   id: PR

      # - name: Test
      #   run: |
      #     echo ${{github.event.workflow_run.id}}
      #     cat << EOF > a.json
      #     ${{ toJSON(github.event.workflow_run.pull_requests) }}
      #     EOF
      #     cat << EOF > b.json
      #     ${{ toJSON(fromJSON(steps.current_pr.outputs.pr)) }}
      #     EOF

      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: Artifact-1
      #     path: a.json

      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: Artifact-2
      #     path: b.json

      - name: Get Current Artifacts
        id: Artifacts
        run: |
          Artifact_0_Name=$(${{ toJSON(github.event.workflow_run.pull_requests) }} | jq -r '.artifacts[0] | .name')
          Artifact_0_ID=$(${{ toJSON(github.event.workflow_run.pull_requests) }} | jq -r '.artifacts[0] | .id')
          Artifact_1_Name=$(${{ toJSON(github.event.workflow_run.pull_requests) }} | jq -r '.artifacts[1] | .name')
          Artifact_1_ID=$(${{ toJSON(github.event.workflow_run.pull_requests) }} | jq -r '.artifacts[1] | .id')
          echo "Artifact_0_Name=$Artifact_0_Name" >> $GITHUB_OUTPUT
          echo "$Artifact_0_Name"
          echo "Artifact_0_ID=$Artifact_0_ID" >> $GITHUB_OUTPUT
          echo "$Artifact_0_ID"
          echo "Artifact_1_Name=$Artifact_1_Name" >> $GITHUB_OUTPUT
          echo "$Artifact_1_Name"
          echo "Artifact_1_ID=$Artifact_1_ID" >> $GITHUB_OUTPUT
          echo "$Artifact_1_ID"

      # - name: Create or update comment
      #   uses: thollander/actions-comment-pull-request@v1
      #   with:
      #     comment_includes: '感謝貢獻！❤️'
      #     message: |
      #       感謝貢獻！❤️
            
      #       下載合併請求測試用翻譯包：
      #       - [${{ steps.Artifacts.outputs.Artifact_1_Name }}](https://nightly.link/${{ github.repository }}/actions/artifacts/${{ steps.Artifacts.outputs.Artifact_1_ID }}.zip)
      #       - [${{ steps.Artifacts.outputs.Artifact_2_Name }}](https://nightly.link/${{ github.repository }}/actions/artifacts/${{ steps.Artifacts.outputs.Artifact_2_ID }}.zip)
