name: Test workflow with upload
on:
  push:
    paths: ['.github/workflows/upload-test.yml']
  pull_request:
    paths: ['.github/workflows/upload-test.yml']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Example artifact for $GITHUB_RUN_ID" >art.txt
      - uses: actions/upload-artifact@v2
        with:
          name: some-artifact
          path: art.txt
