name: Test workflow with upload
on:
  push:
    paths: ['.github/workflows/upload-test.yml']
  pull_request:
    paths: ['.github/workflows/upload-test.yml']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Example artifact for $GITHUB_RUN_ID" >art-1.txt
          echo "Example artifact for $GITHUB_RUN_ID" >art-2.txt
      - uses: actions/upload-artifact@v2
        with:
          name: Artifact-1
          path: art-1.txt
      - uses: actions/upload-artifact@v2
        with:
          name: Artifact-2
          path: art-2.txt
